# Generated by Django 3.2.7 on 2022-09-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_auto_20220927_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='profile_pics/avatar.png', upload_to='profile_pics'),
        ),
    ]
